name: feature-pipeline

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  feature_pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.7.1 # Specify the Poetry version, if needed

    - name: Install Dependencies
      run: poetry install

    - name: Install Hopsworks
      run: pip install hopsworks

    - name: Run feature generation script
      env: 
        HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
      run: poetry run jupyter nbconvert --to notebook --execute notebooks/12_feature_pipeline.ipynb
